- hosts: "{{ lstor_target }}"
  become: yes
  tasks:
    - name: "Add bcacehfs-testing PPA"
      apt_repository:
        repo: "ppa:raof/bcachefs"
        state: present

    - name: "Install required packages"
      apt:
        name:
          - bcachefs-tools
          - linux-bcachefs
        update_cache: yes